### ISSUE TITLE
how to use trip gracefully？

### ISSUE THREAD

**Issue by JamCh01** [littlecodersh/trip#10]
here is my code
```python
import trip

PROXIES = {
    'http': 'socks5://127.0.0.1:1086',
    'https': 'socks5://127.0.0.1:1086'
}


@trip.coroutine
def test():
    r = yield trip.get(url='https://github.com/shadowsocks/shadowsocks-android/releases/download/v4.2.5/shadowsocks-nightly-4.2.5.apk',
                       proxies=PROXIES,
                       stream=True).iter_content(chunk_size=1024)


def main():
    with open('shadowsocks-nightly-4.2.5.apk', 'wb') as f:
        for chunk in trip.run(test):
            f.write(chunk)


if __name__ == "__main__":
    main()
```

I wanna download a file, output is here
```
$ python2 test.py
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    main()
  File "test.py", line 18, in main
    for chunk in trip.run(test):
  File "/usr/local/lib/python2.7/site-packages/trip/api.py", line 153, in run
    IOLoop.current().run_sync(fn)
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "test.py", line 13, in test
    stream=True).iter_content(chunk_size=1024)
AttributeError: 'Future' object has no attribute 'iter_content'
```

**Comment by littlecodersh** [comment]
First of all, make sure your `trip` is up to date.
```python
python -m pip install trip -U
```

Then, this is my suggestion:
```python
import trip

PROXIES = {
    'http': 'socks5://127.0.0.1:1086',
    'https': 'socks5://127.0.0.1:1086'
}
url = 'https://github.com/shadowsocks/shadowsocks-android/releases/download/v4.2.5/shadowsocks-nightly-4.2.5.apk'

@trip.coroutine
def test():
    r = yield trip.get(url, proxies=PROXIES, stream=True)
    with open('shadowsocks-nightly-4.2.5.apk', 'wb') as f:
        for cf in r.iter_content(1024):
            chunk = yield cf
            f.write(chunk)

if __name__ == "__main__":
    trip.run(test)
```

**Comment by JamCh01** [comment]
It will raise ```ValueError: IOStream is not idle; cannot convert to SSL```
```python
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    trip.run(test)
  File "/usr/local/lib/python3.6/site-packages/trip/api.py", line 153, in run
    IOLoop.current().run_sync(fn)
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "test.py", line 12, in test
    r = yield trip.get(url=url, proxies=PROXIES, stream=True)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/trip/sessions.py", line 424, in send
    r = yield self.adapter.send(req, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/trip/adapters.py", line 259, in send
    source_ip=host, source_port=port)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 189, in connect
    server_hostname=host)
  File "/usr/local/lib/python3.6/site-packages/tornado/iostream.py", line 1171, in start_tls
    raise ValueError("IOStream is not idle; cannot convert to SSL")
ValueError: IOStream is not idle; cannot convert to SSL

```

**Comment by littlecodersh** [comment]
@jamcplusplus 把tornado和trip的版本号给我一下。
```bash
python -m pip show tornado trip
```

**Comment by JamCh01** [comment]
```
$ pip3 show tornado trip
Name: tornado
Version: 4.5.2
Summary: Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
Home-page: http://www.tornadoweb.org/
Author: Facebook
Author-email: python-tornado@googlegroups.com
License: http://www.apache.org/licenses/LICENSE-2.0
Location: /usr/local/lib/python3.6/site-packages
Requires:
---
Name: trip
Version: 0.0.6
Summary: Async HTTP for humans, coroutine Requests.
Home-page: https://github.com/littlecodersh/trip
Author: LittleCoder
Author-email: i7meavnktqegm1b@qq.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: requests, tornado
```

**Comment by littlecodersh** [comment]
@jamcplusplus 邮件我你的qq？我qq你

**Comment by JamCh01** [comment]
@littlecodersh 已经向您发送信息了~请查看~
