### ISSUE TITLE
AttributeError: 'HTTPHeaderDict' object has no attribute 'get_all'

### ISSUE THREAD

**Issue by afetmin** [littlecodersh/trip#13]
前天用时没问题
今天使用时出了错
```
"C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\gen.py", line 1069, in run 
yielded = self.gen.send(value)

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\trip\sessions.py", line 430, in send
    r = self.prepare_response(req, r)

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\trip\sessions.py", line 292, in prepare_response
    MockResponse(headerDict), MockRequest(req))

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\cookiejar.py", line 1664, in extract_cookies
    for cookie in self.make_cookies(response, request):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\http\cookiejar.py", line 1581, in make_cookies
    rfc2965_hdrs = headers.get_all("Set-Cookie2", [])
AttributeError: 'HTTPHeaderDict' object has no attribute 'get_all'
```

**Comment by lovezeropython** [comment]
我也遇到同样的问题

**Comment by littlecodersh** [comment]
@afetmin @lovezeropython 
可能是依赖库版本过旧，可以尝试更新依赖库版本。
```bash
pip install trip -U
```
更新后如果还有问题请将如下命令的结果发给我：
```bash
pip show trip requests tornado
```

**Comment by lovezeropython** [comment]
```bash
Name: trip
Version: 0.0.9
Summary: Async HTTP for humans, coroutine Requests.
Home-page: https://github.com/littlecodersh/trip
Author: LittleCoder
Author-email: i7meavnktqegm1b@qq.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: requests, tornado
---
Name: requests
Version: 2.18.4
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: certifi, chardet, idna, urllib3
---
Name: tornado
Version: 4.5.3
Summary: Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
Home-page: http://www.tornadoweb.org/
Author: Facebook
Author-email: python-tornado@googlegroups.com
License: http://www.apache.org/licenses/LICENSE-2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: backports-abc, singledispatch, certifi
```

@littlecodersh 

```python
/usr/local/bin/python3.6 /Users/songhao/py/TouTiaoShare/trip模块.py
Traceback (most recent call last):
  File "/Users/songhao/py/TouTiaoShare/trip模块.py", line 14, in <module>
    trip.run(main)
  File "/usr/local/lib/python3.6/site-packages/trip/api.py", line 156, in run
    IOLoop.current().run_sync(fn)
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/songhao/py/TouTiaoShare/trip模块.py", line 11, in main
    r = yield trip.get('https://httpbin.org/get')
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.6/site-packages/trip/sessions.py", line 430, in send
    r = self.prepare_response(req, r)
  File "/usr/local/lib/python3.6/site-packages/trip/sessions.py", line 292, in prepare_response
    MockResponse(headerDict), MockRequest(req))
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py", line 1664, in extract_cookies
    for cookie in self.make_cookies(response, request):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/cookiejar.py", line 1581, in make_cookies
    rfc2965_hdrs = headers.get_all("Set-Cookie2", [])
AttributeError: 'HTTPHeaderDict' object has no attribute 'get_all'
```

**Comment by littlecodersh** [comment]
@lovezeropython 你上面显示的是2.7的第三方包版本，下面使用的是3.6的环境
