### ISSUE TITLE
依赖的request是版本是多少呢？

### ISSUE THREAD

**Issue by linfengtingxue** [littlecodersh/trip#3]
>>> import trip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/trip/__init__.py", line 12, in <module>
    from .api import (
  File "/usr/local/lib/python2.7/site-packages/trip/api.py", line 10, in <module>
    from . import sessions
  File "/usr/local/lib/python2.7/site-packages/trip/sessions.py", line 21, in <module>
    from requests.sessions import (
ImportError: cannot import name preferred_clock

>>> requests.__version__
'2.13.0'

我看requests的sessions文件里并没有preferred_clock函数。。。

**Comment by guoweikuang** [comment]
使用`pip uninstall requests` 卸载掉旧的版本，再`pip install requests` 安装最新版本就可以了，

**Comment by littlecodersh** [comment]
2.18.4，直接升级也行：

```bash
python -m pip install requests -U
```
